# Generated by Django 2.1.7 on 2019-03-04 15:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('depart', models.CharField(max_length=10)),
                ('cid', models.IntegerField(validators=[django.core.validators.MinValueValidator(100), django.core.validators.MaxValueValidator(699)])),
                ('name', models.CharField(max_length=40)),
                ('desc', models.CharField(blank=True, max_length=5000, null=True)),
                ('cred', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(6)])),
            ],
        ),
    ]
