# Generated by Django 2.1.7 on 2019-03-07 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coursegraph', '0003_auto_20190307_1444'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='course',
            unique_together=set(),
        ),
    ]
